### ISSUE TITLE
Globally set default_permissions per plugin

### ISSUE THREAD

**Issue by jaymaart** [hypergonial/hikari-arc#6]
### Summary

Pretty much be able to set `default_permissions` for the entire plugin rather than each individual command you add within that plugin.

### Why is this needed?

Pretty much just removes the pain of adding `default_permissions` to every command.

### Ideal implementation

ideally would be nice to just be able to set it within the implementation of a plugin like so
```py
plugin = GatewayPlugin(name="admin_cmds", default_permissions=..)
```

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by hypergonial** [comment]
Implemented in [3403713c](https://github.com/hypergonial/hikari-arc/commit/3403713c122fd2ba6ba934fd49b6ff958253b02d).
