### ISSUE TITLE
Add meta decorators

### ISSUE THREAD

**Issue by mplatypus** [hypergonial/hikari-arc#7]
### Summary

Add meta decorators to all commands, sub-commands, and plugins, and also, be able to attach them to the options, within a command.

### Why is this needed?

This is needed because I will not stop bugging you to make it, and it would be useful for others.

### Ideal implementation

Here is my idea:

Have some sort of basic decorator, like this:

```python
@arc.add_metadata(arc.Metadata(example="beans"))
```

but then, if people want to make custom metadata, they can subclass `arc.Metadata` and add their arguments to it.

I have no idea, how adding them to an option would work, so I will leave that up to you, or we can have a talk about it idk.

### Checklist

- [x] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by hypergonial** [comment]
I currently do not feel like this fits into the main library in a nice way. Perharps as an extension? Closing for now.
